### ISSUE TITLE
Add support for account deletion

### ISSUE THREAD

**Issue by dschofie** [Santiago-Labs/telophasecli#79]
We want to allow explicit account deletion by setting a field `Delete: true` in the Accounts: field

For example,
```yaml
    Accounts:
      - Email: "danny@example.com"
        Name: "MyAccount"
        Delete: true
```
